# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Publish Blog to Azure VM

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name : ready for deploy first server (excute shell script)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BLOG_SSH_IP }}
        username: ${{ secrets.BLOG_SSH_ID }}
        key: ${{ secrets.BLOG_SSH_KEY }}
        port: ${{ secrets.BLOG_SSH_PORT }}
        script_stop: true
        script: "./turn_off_blog.sh"

    - name: Sleep for 60 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'

    - name: upload file to server1
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.BLOG_SSH_IP }}
        username: ${{ secrets.BLOG_SSH_ID }}
        key: ${{ secrets.BLOG_SSH_KEY }}
        port: ${{ secrets.BLOG_SSH_PORT }}
        source: "build/**/*.jar"
        target: "~/"
        rm: false

    - name : excute service (server1)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BLOG_SSH_IP }}
        username: ${{ secrets.BLOG_SSH_ID }}
        key: ${{ secrets.BLOG_SSH_KEY }}
        port: ${{ secrets.BLOG_SSH_PORT }}
        script_stop: true
        script: "./run_blog.sh"
